# Generated by Django 3.0.6 on 2021-01-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210115_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat',
            field=models.ManyToManyField(related_name='_chatmessage_chat_+', to='blog.ChatBox'),
        ),
    ]
