# Generated by Django 3.0.6 on 2021-01-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_chatmessage_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chats',
            field=models.ManyToManyField(blank=True, related_name='_profile_chats_+', to='blog.ChatBox'),
        ),
    ]
