# Generated by Django 3.1.5 on 2021-02-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_profile_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='_profile_posts_+', to='blog.Post'),
        ),
    ]
