# Generated by Django 3.1.5 on 2021-02-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_profile_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_online',
        ),
    ]
