# Generated by Django 3.1.5 on 2021-03-02 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_profile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbox',
            name='last_message_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
