# Generated by Django 3.1.5 on 2021-03-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_chatbox_last_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='last_message_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
