# Generated by Django 3.0.6 on 2021-01-14 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210114_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendinvitation',
            name='profile_from',
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='profile_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.Profile'),
        ),
        migrations.RemoveField(
            model_name='friendinvitation',
            name='profile_to',
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='profile_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.Profile'),
        ),
    ]
