# Generated by Django 3.0.6 on 2021-01-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210115_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='displayed',
            field=models.BooleanField(default=False),
        ),
    ]
