# Generated by Django 3.1.5 on 2021-01-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210119_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='_chatbox_messages_+', to='blog.ChatMessage'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
